[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Handle SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true
